### ISSUE TITLE
Build fails due to eigen failing to download

### ISSUE THREAD

**Issue by bennybp** [pulsar-chem/Pulsar-Meta#4]
Currently, we fetch eigen from bitbucket via a cmake external project. This (now?) fails, since bitbucket will redirect the download to an https URL. SSL is not generally supported by cmake (unless specially compiled in) so this causes the build to fail.

The only workaround I can think of is to require the user to manually download/install eigen. Or we have to start hosting a copy ourselves somewhere.

**Comment by ryanmrichard** [comment]
Lol.  Yeah that's one problem I had with Travis...

**Comment by ryanmrichard** [comment]
This is fixed in #5
